### ISSUE TITLE
Error while scrobbling selected tracks: Cached

### ISSUE THREAD

**Issue by Leyharu** [SHOEGAZEssb/Last.fm-Scrubbler-WPF#102]
Hello, I just can't seem to manage to scrobble my .json file. 
The "Error while scrobbling selected tracks: Cached" error is back again.
I have the last version of the app.

Thanks for the help!

**Comment by BurtoBurtoBurto** [comment]
Hi there-

I'm having the same issue, just started today, using the Media Player Database Scrobbler (.xml).
I had had no problems for the last 2 months, using the same parsed database file, daily (going 2k scrobbles at a time).

Using the latest beta version 1.24.0.0.

I tried it using the last Scrubbler version, then updated to the new one, and same issue.

I also tried to unlink from the last.fm applications page, logout and log back in on the Scrubbler, and am still having the same problems.

Please advise! Thanks!

**Comment by 3lit3b3ast** [comment]
having the same issue, worked fine until i scrobbled around 2.5k then started getting the cache message, might just have to wait for the scrobble count to reset

**Comment by SHOEGAZEssb** [comment]
With this error you just have to wait and try again a few hours / days later

**Comment by jaredknppr** [comment]
_(reposting from the other thread I found about this same issue)_

I updated the Scrubbler software to 1.29 right before the issue began, but I tried again on 1.27 to see what would happen and.... no success on the older version either. I did file parse uploads for 2 days, 2,600 scrobbles each day, then got the error message on the third doing the uploads all in rapid succession, no more than 5 minutes apart. I deleted the Scrubbler from my list of connected apps on the Last.fm site, I logged out from the Scrubbled and logged back in, I restarted my computer. None of those things worked, and I tried again about 12h after the first failure to see if time helped, and I still got the cache error. I tried a few different upload files, and I also chose a few different days as the upload "timestamp."

Has anyone else come up with a solution for reset or identified an issue that could be behind the cache error? I did verify that the days into which I was trying to upload my scrobbles didn't have more than 400 tracks each that would push me over the daily max, so that can't be my problem either.
