### ISSUE TITLE
Error while Scrobbling Selected Tracks: Cached

### ISSUE THREAD

**Issue by kibummedout** [SHOEGAZEssb/Last.fm-Scrubbler-WPF#146]
I've been trying to import for a while now and it keeps giving me the error message in the title. There was an issue similar that said to remove the scrubbler from last.fm applications but I've done that and to no avail. Then I disconnected and waited a 24 hours and still nothing. When it finally did scrobble it was only 896 verses the 2600 it usually scrobbles for me. I then edited the file to just the ones it didn't scrobble. Yet again, it gave me the error. Coincidentally my roommate is also importing and she is getting the same message. Help please :'(

**Comment by SHOEGAZEssb** [comment]
Its probably because you and your roommate use the same internet connection - which last.fm detects and limits.
The scrobble limit of 3000 is enforced on the whole network. So you either can try taking turns importing scrobbles or use a different internet connection. That would be my suggestion, unfortunately last.fms scrobble limit is a bit weird and sometimes acts up without having reached the limit. In that case another suggestion would be to still take turns and use smaller batches
